---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
library(sTraitChange)
```

# sTraitChange_Analyses

<!-- badges: start -->
<!-- badges: end -->

The goal of sTraitChange_Analyses project is to provide the full workflow as well as the data needed to reproduce the analyses for the manuscript 'Changes in phenology mediate vertebrate population responses to temperature globally' by Radchuk et al. (submitted). The analyses in this repository rely heavily on the functions available from [sTraitChange](https://github.com/radchukv/sTraitChange) package. 

## System requirements

### Hardware requirements

We recommend a computer with following specs to run the analyses in this R project:     
- RAM: 16+ GB     
- CPU: 4+ cores.   

### Software requirements

This R project was tested on:       
- macOS: Sequioa 15.0.1   
- Windows:      

In order to run the analyses, the following R packages must be installed: 
``` r
install.packages(c('climwin', 'sTraitChange', 'metafor', 'patchwork', 'spaMM', 'ape',
'RRphylo', 'rtrees', 'geiger', 'corrplot', 'ggtext', 'grafify', 'magrittr', 'tidyverse'))
```

The following versions of these packages were used when the R project `sTraitChange_Analyses` was tested:
``` r
"ape 5.8"
"climwin 1.2.3"
"corrplot 0.94"
"geiger 2.0.11"
"ggtext 0.1.2"
"metafor 4.6.0"
"patchwork 1.2.0"
"rtrees 1.0.3"
"spaMM 4.5.0"
"sTraitChange 0.0.0.900"
"tidyverse 2.0.0"
"grafify 5.0.0.1"
"magrittr 2.0.3"
"RRphylo 2.8.1"
```

## Structure

This project contains the following folders:  
- data: datasets used in the analyses;   
- output_SEM_all: general outputs from the analyses based on structural equation models (SEMs);   
- output_forSEM_precip and output_forSEM_temp: the prepared datasets ready for running SEMs using, respectively, precipitation and temperature as climate variables;      
- output_fSEM_precip and output_fSEM_temp: the output from the SEM analyses, obtained, using, respectively, precipitation and temperature as climate variables. These outpus are used later on in meta-analyses;     
- output_fSEM_noDD_precip and output_fSEM_noDD_temp: the output from the SEM analyses conducted without population size included in SEM (sensitivity analyses: for details, see the manuscript). Some of these results are intermediate and are later used in meta-analyses. These results are obtained, using, respectively, precipitation and temperature as climate variables;    
- output_all_noDD: general output from the analyses conducted when population size is not included in the SEM;   
- output_all: general output obtained from the complete workflow;    
- plots_ms: plots used in the manuscript;   
- tables: tables produced during the analyses;   
- scripts: all R scripts used in the workflow (more details below).    

## Instructions for use

The scripts are numbered in the logical order in which they are used in the analyses. The scripts  pertaining to sliding window analyses will not run out of the box because relevant climate datasets could not be shared in the repo (due to its prohibitively big size). In order to run those scripts, the user will have to download the climate data from the respective sources mentioned in Supplementary materials (Table S7) and place them in the respective directory on the path (./data).  

Brief description of what each script does:   
- **1.1_DataPrep_Clim.R**: prepares climate data for sliding window analyses using `climwin` package (will not run directly, see above!).  
- **1.2_DataPrep_Biol.R**: prepares biological data for sliding window analyses using `climwin` package.    
- **2_climwin.R**: performs sliding window analyses (will not run directly, see above!);    
- **3.0_PrepData_forSEM.R**: prepares the data for SEM analyses;   
- **3.1_SEM.R**: performs SEM analyses;    
- **4.0_Descriptive.R**: provides description of the total dataset;   
- **4.1_ClimwinWindows.R**: describes results from sliding window analyses;   
- **4.2_NonLinAssumption.R**: assesses non-linearity assumptions;   
- **5.1_Phylo_prep.R**: prepares a mega-tree for performing meta-analyses that account for phylogenetic relatedness;   
- **5.2.1_Metaanalysis_Temp.R**: meta-analyses focusing on temperature as climate variable;   
- **5.2.2_Metaanalysis_Precip.R**: meta-analyses focusing on precipitation as climate variable;   
- **5.3.1_Metaanalysis_Temp_noDD.R** & **5.3.2_Metaanalysis_Precip_noDD.R**: meta-analyses focusing, respectively, on temperature and precipitation as climate variables and performed without the population size included in SEM (sensitivity analyses);    
- **5.4_Metaanalysis_AcrossPhylogenies.R**: a script running meta-analyses across 100 posterior phylogenies;    
- **5.5_Metaanalysis_HeterogeneityPaths.R**: a script explaining the heterogeneity in the SEM paths with hypothesized predictors;   
- **5.6_Metaanalysis_Heterogeneity_FineCatNames.R**: assessing the impact of the fine trait category on heterogeneity in the phenotypic responses to climate;   
- **5.7_Metaanalysis_Temp_perTaxon.R**: meta-analyses focusing on effects of temperature on phenological traits, separate per taxon;   
- **5.8_Metaanalysis_AcrossPhylogenies_perTaxon.R**: running meta-analyses per taxon across 100 posterior phylogenies;   
- **6_pDeltaAIC.R**: exploration of the potential impact that pDeltaAIC has on the results;   
- **7_Figures_MS.R**: Figures used in the manuscript.    

## Support

For any further information, please contact radchuk@izw-berlin.de.
